[[constraint]]
  name = "github.com/contribsys/faktory"
  version = "v0.8.0-1"

[[constraint]]
  branch = "master"
  name = "github.com/contribsys/faktory_worker_go"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  name = "github.com/go-chi/render"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/apex/log"
  version = "v1.0.0"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.5.0"

[[constraint]]
  name = "github.com/volatiletech/sqlboiler"
  version = "v3.0.0-rc9"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.2.2"

[prune]
  go-tests = true
  unused-packages = true
