// Code generated by "stringer -type=VCS"; DO NOT EDIT.

package models

import "strconv"

const _VCS_name = "GitSubversionMercurialBazaar"

var _VCS_index = [...]uint8{0, 3, 13, 22, 28}

func (i VCS) String() string {
	i -= 1
	if i < 0 || i >= VCS(len(_VCS_index)-1) {
		return "VCS(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _VCS_name[_VCS_index[i]:_VCS_index[i+1]]
}
